from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(501, 578)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 461, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 310, 461, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Button_GenerateKey = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Button_GenerateKey.setMinimumSize(QtCore.QSize(0, 40))
        self.Button_GenerateKey.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.Button_GenerateKey)
        self.ButtonCopy_OpenKey = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.ButtonCopy_OpenKey.setMinimumSize(QtCore.QSize(0, 40))
        self.ButtonCopy_OpenKey.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.ButtonCopy_OpenKey)
        self.ButtonCopy_CloseKey = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.ButtonCopy_CloseKey.setMinimumSize(QtCore.QSize(0, 40))
        self.ButtonCopy_CloseKey.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.ButtonCopy_CloseKey)
        self.Button_delete = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Button_delete.setMinimumSize(QtCore.QSize(0, 40))
        self.Button_delete.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.Button_delete)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Генерация ключей"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Введите размер рюкзака..."))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Введите значения рюкзака..."))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Введите u..."))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "Открытый ключ"))
        self.Button_GenerateKey.setText(_translate("Dialog", "Генирировать ключи"))
        self.ButtonCopy_OpenKey.setText(_translate("Dialog", "Копировавть открытый ключ"))
        self.ButtonCopy_CloseKey.setText(_translate("Dialog", "Копировать закрытый ключ"))
        self.Button_delete.setText(_translate("Dialog", "Очистить поля"))